name: resume_fix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your required packages
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  pdf: 3.10.4
  printing: ^5.12.0
  open_filex: ^4.7.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.10
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Icon/
    - .env
